### ISSUE TITLE
New user for every session

### ISSUE THREAD

**Issue by niyando** [ankane/archer#1]
Hi, 
Thanks for this awesome gem.

Is there a way I can set a new user for every session so that it doesn't keep updating the same record? It could be something like current date time.

How can I achieve that?

**Comment by niyando** [comment]
Passing the env var while running the command doesn't change `Archer.user` for me

**Comment by ankane** [comment]
Hey @niyando, check out the docs for how to set the user manually. I'm not sure how to reproduce the issue in the 2nd comment (try restarting spring if you use that).

**Comment by niyando** [comment]
@ankane this works after I stop the spring in development. I guess this should not be an issue on production. Thank you. Cheers!

**Comment by ankane** [comment]
np
