### ISSUE TITLE
Adding archer-rails results in exceptions running rails console on Heroku

### ISSUE THREAD

**Issue by ryanfb** [ankane/archer#3]
If I put `archer-rails` in my `Gemfile` and then try to use `heroku run rails console`, I get the following exception:

```
Traceback (most recent call last):
        8: from /app/vendor/bundle/ruby/2.7.0/gems/archer-rails-0.2.1/lib/archer/engine.rb:11:in `block (2 levels) in <class:Engine>'
        7: from /app/vendor/bundle/ruby/2.7.0/gems/archer-rails-0.2.1/lib/archer.rb:47:in `save'
        6: from /app/vendor/bundle/ruby/2.7.0/gems/archer-rails-0.2.1/lib/archer.rb:70:in `quietly'
        5: from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/logger_silence.rb:18:in `silence'
        4: from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/logger_thread_safe_level.rb:52:in `log_at'
        3: from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/logger_silence.rb:18:in `block in silence'
        2: from /app/vendor/bundle/ruby/2.7.0/gems/archer-rails-0.2.1/lib/archer.rb:71:in `block in quietly'
        1: from /app/vendor/bundle/ruby/2.7.0/gems/archer-rails-0.2.1/lib/archer.rb:49:in `block in save'
/app/vendor/bundle/ruby/2.7.0/gems/archer-rails-0.2.1/lib/archer.rb:58:in `history_object': uninitialized constant Archer::Readline (NameError)
Did you mean?  Reline
```

Strangely, this didn't happen the *first* time I brought up a Heroku Rails console after installing `archer-rails` following the instructions, but only the *second* time and all times after (I wanted to check that the command history was working).

I've also tried having `archer-rails` included for all groups instead of just production, as well as using `heroku run bundle exec rails console` just in case, but I get the same error. I've added/run the migrations as per the instructions.

This is with Rails 6.1.0 under Ruby 2.7.2 with Bundler 2.2.4.

**Comment by ankane** [comment]
Hey @ryanfb, thanks for reporting. Can you paste the value of `IRB.CurrentContext.io.class`?

**Comment by ryanfb** [comment]
On production Heroku without the `archer-rails` gem (since I can't bring up a console with it), that gives me: `IRB::ReidlineInputMethod`

**Comment by ankane** [comment]
Hey @ryanfb, think I found the issue. Can you try running the GitHub version?

```ruby
gem 'archer-rails', github: 'ankane/archer'
```

**Comment by ryanfb** [comment]
Thanks, that fixed it! Works on Heroku now with history between sessions!

**Comment by ankane** [comment]
Awesome, just put out a new release (0.2.2).
