### ISSUE TITLE
Is there a way to add the ability to not save a session before exiting?

### ISSUE THREAD

**Issue by sebastienb** [ankane/archer#4]
In some cases you might not want a session to be saved in the DB as clear text. Is there a way to maybe run a command before exiting that would let archer know not to save this session?

**Comment by ankane** [comment]
Hey @sebastienb, currently, the only way is to clear the entire history (`Archer.clear`), but there could be an option like `Archer.save_session = false`.

**Comment by ankane** [comment]
Added in the commit above. Thanks for the suggestion!
