### ISSUE TITLE
Feature Proposal: Create/Save Event Hook & Default User Method

### ISSUE THREAD

**Issue by dinsley** [ankane/archer#6]
Hi there!

I had been looking at doing something similar to this project in order to aggregate IRB history into our observability platform for any executions that might happen within Heroku Dynos via Rails console, so we can have historical record of the activity and a general audit trail incase of incidents. Would you be open to accepting a pull request(s) that would extend this project in the following ways:

1) Adds a hook so that the history log entry could be sent or processed elsewhere (in our use case this would be New Relic)

2) Adds the ability to define a user callback method that gets executed to determine the default user to send. We use Heroku and we're looking at using the Heroku CLI to determine the authenticated user as a default.

I'm happy to submit a PR if you think those two pieces would be suitable for the project.

**Comment by ankane** [comment]
Hi @dinsley, thanks for the suggestions. Auditing isn't really a goal of this project, but you may want to check out [console1984](https://github.com/basecamp/console1984) and [audits1984](https://github.com/basecamp/audits1984). Also, you can set the user with `Archer.user = ...` ([docs](https://github.com/ankane/archer#configuration)).
