### ISSUE TITLE
Multiline command support

### ISSUE THREAD

**Issue by swrobel** [ankane/archer#7]
Multi-line commands seem to be broken up into their individual lines by Archer, which makes it hard to re-run them. Contrived example:

```ruby
[1,2,3].each do |item|
  puts item
end
```
Pressing up within the same console session restores the entire 3-line command, but upon starting a new console and pressing up, I can only select a single line, ex:
```
irb(main):001* [1,2,3].each do |item|
irb(main):002*
```
However, pressing the up arrow on the second line simply moves up to the first line, instead of letting me choose the `puts item` line from the history to even attempt to piece the multi-line command back together.

**Comment by ankane** [comment]
Hi @swrobel, thanks for reporting! Added support in the commit above.
